version: '3.7'

volumes:
  node_modules:
  public_packs:
  public_packs_test:

services:
  web:
    build: .
    # For now, the entrypoint is just some command that will never fail.
    # Running the rails server feels like a reasonable thing to do here
    # instead, but can often crash just because you've done a `git pull` that
    # brings in newer dependencies. I've seen some examples online where the
    # entrypoint is set to install dependencies before starting the server,
    # just to avoid that issue. That feels pretty weird to me, so I've
    # decided not to do anything for now in favor of forcing the user to do
    # everything manually via `make shell`. I definitely would like running
    # the server to be a one command thing, though, so we'll need to
    # revisit this someday.
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - DATABASE_URL=mysql2://root:@db
      - DISABLE_SPRING=1

      # TODO: Switch to setting `DatabaseCleaner.url_whitelist = ['mysql2://root:@db']`
      # in WcaOnRails/spec/support/database_cleaner.rb once a new version of
      # Database Cleaner comes out. See
      # https://github.com/DatabaseCleaner/database_cleaner/issues/572 for more
      # information.
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true

    volumes:
      - .:/app

      - node_modules:/app/node_modules/
      - public_packs:/app/public/packs/
      - public_packs_test:/app/public/packs-test

      # This is kind of weird: there are a couple of things outside of the
      # WcaOnRails directory that the Rails app expects to exist.
      - ../secrets:/secrets
      - ../.ruby-version:/.ruby-version
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
